name: Build iOS
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4 # تحديث إلى v4

      - name: Set up Python
        uses: actions/setup-python@v5 # تحديث إلى v5
        with:
          python-version: '3.10'

      - name: Install Tools
        run: |
          python -m pip install kivy-ios
          brew install autoconf automake libtool pkg-config

      - name: Create Project
        run: |
          toolchain build python3 kivy
          toolchain create "Cinemana" .
          
      - name: Upload Result
        uses: actions/upload-artifact@v4 # هذا هو التحديث الأهم لحل المشكلة
        with:
          name: iOS-Project
          path: .
